title: My README Site
description: A simple custom Jekyll theme

# Ensure kramdown uses GitHub-flavored-markdown (GFM) so pipe-tables render
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
